/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Lock__factory } from "./Lock__factory";
export { SmartContractTronix__factory } from "./SmartContractTronix__factory";
export { Tronix__factory } from "./Tronix__factory";
