/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Lock } from "./Lock";
export type { SmartContractTronix } from "./SmartContractTronix";
export type { Tronix } from "./Tronix";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export { SmartContractTronix__factory } from "./factories/SmartContractTronix__factory";
export { Tronix__factory } from "./factories/Tronix__factory";
